apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-deployment-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops
  template:
    metadata:
      labels:
        app: gitops
    spec:
      containers:
      - name: gitops
        image: docker.io/ayuse/gitops-go-app:latest
        imagePullPolicy: IfNotPresent
